version: 0.2

phases:
  install:
    runtime-versions:
      # You can specify runtime versions for languages like python, node, etc.
      # We will install Terraform manually for precise version control.
      python: 3.11
    commands:
      - "TF_VERSION=1.8.2"
      - "wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - "unzip terraform_${TF_VERSION}_linux_amd64.zip"
      - "mv terraform /usr/local/bin/"

  pre_build:
    commands:
      - "echo Initializing Terraform"
      - "terraform init"

  build:
    commands:
      - "echo Validating Terraform configuration"
      - "terraform validate"
      - "echo Running Terraform plan"
      # The AWS region is passed via the default in variables.tf
      # AWS credentials are automatically provided by the CodeBuild execution role.
      - "terraform plan -out=tfplan"
      - "echo Applying Terraform plan"
      - "terraform apply -auto-approve tfplan"

  post_build:
    commands:
      - "echo Build completed on `date`"

# This is equivalent to the artifacts section in cloudbuild.yaml
artifacts:
  files:
    - 'tfplan'
  # You can optionally discard paths if you only want the plan artifact
  discard-paths: yes