steps:
  # Initialize Terraform. This step also downloads the necessary providers.
  - name: 'hashicorp/terraform:1.8.2'
    id: 'init'
    entrypoint: 'terraform'
    args: ['init']

  # Create a Terraform plan.
  # We use the -var flag to pass the project ID and region.
  # These values are supplied by the 'substitutions' section below.
  - name: 'hashicorp/terraform:1.8.2'
    id: 'plan'
    entrypoint: 'terraform'
    args:
      - 'plan'
      - '-out=tfplan'
      - '-var=gcp_project_id=${_GCP_PROJECT_ID}'
      - '-var=gcp_region=${_GCP_REGION}'
    waitFor: ['init']

  # Apply the Terraform plan.
  - name: 'hashicorp/terraform:1.8.2'
    id: 'apply'
    entrypoint: 'terraform'
    args:
      - 'apply'
      - '-auto-approve'
      - 'tfplan'
    waitFor: ['plan']

options:
      logging: CLOUD_LOGGING_ONLY